apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dese-ea-plan-v5

# Inherit from base
resources:
  - ../../base

# Production-specific overrides
replicas:
  - name: dese-ea-plan-v5
    count: 5  # Increased replicas for high availability

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
    target:
      kind: Deployment
      name: dese-ea-plan-v5

  - patch: |-
      - op: add
        path: /spec/template/metadata/annotations/self-healing
        value: "enabled"
      - op: add
        path: /spec/template/metadata/annotations/rollout-strategy
        value: "canary"
      - op: add
        path: /spec/template/metadata/annotations/drift-prevention
        value: "enforced"
    target:
      kind: Deployment
      name: dese-ea-plan-v5

labels:
  - pairs:
      environment: production
      app.kubernetes.io/instance: dese-ea-plan-v5-prod
      app.kubernetes.io/version: "5.2.0"

images:
  - name: dese-ea-plan-v5
    newTag: prod-5.2.0

# HorizontalPodAutoscaler for self-healing
resources:
  - hpa.yaml

