# =========================================================
# Dese EA Plan v5.0 - AIOps Observer Extensions
# Grafana + Loki + Tempo + SEO Observer
# =========================================================
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: grafana
      namespace: monitoring
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: grafana
      template:
        metadata:
          labels:
            app: grafana
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:11.2.0
              ports:
                - containerPort: 3000
              volumeMounts:
                - name: grafana-storage
                  mountPath: /var/lib/grafana
          volumes:
            - name: grafana-storage
              emptyDir: {}
  - apiVersion: v1
    kind: Service
    metadata:
      name: grafana
      namespace: monitoring
    spec:
      ports:
        - port: 3000
          targetPort: 3000
      selector:
        app: grafana

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: loki
      namespace: monitoring
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: loki
      template:
        metadata:
          labels:
            app: loki
        spec:
          containers:
            - name: loki
              image: grafana/loki:3.2.1
              ports:
                - containerPort: 3100

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: tempo
      namespace: monitoring
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: tempo
      template:
        metadata:
          labels:
            app: tempo
        spec:
          containers:
            - name: tempo
              image: grafana/tempo:2.5.0
              ports:
                - containerPort: 3200
              volumeMounts:
                - name: tempo-config
                  mountPath: /etc/tempo
                - name: tempo-storage
                  mountPath: /tmp/tempo
          volumes:
            - name: tempo-config
              configMap:
                name: tempo-config
            - name: tempo-storage
              emptyDir: {}
