# =========================================================
# Dese EA Plan v5.0 - GitOps Setup (Flux CD)
# =========================================================
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
- kind: ServiceAccount
  name: flux
  namespace: flux-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-controller
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-controller
  template:
    metadata:
      labels:
        app: flux-controller
    spec:
      serviceAccountName: flux
      containers:
      - name: flux
        image: fluxcd/flux:v2.2.0
        args:
        - --watch-all-namespaces=true
        - --log-level=info
        - --manifest-generation=true
        - --memcached-service=
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-url=git@github.com:desesonpro/desewebv5-gitops.git
        - --git-branch=main
        - --git-path=manifests
        - --git-poll-interval=30s
        - --sync-interval=5m
        - --k8s-allow-namespace=monitoring
        - --k8s-allow-namespace=flux-system
        volumeMounts:
        - name: git-keygen
          mountPath: /var/fluxd/keygen
          readOnly: true
      volumes:
      - name: git-keygen
        emptyDir: {}
