apiVersion: apps/v1
kind: Deployment
metadata:
  name: seo-observer
  namespace: production
spec:
  template:
    spec:
      initContainers:
        - name: event-generator
          image: node:18-alpine
          command:
            - sh
            - -c
            - |
              echo "AIOps event generator starting..."
              while true; do
                node -e "
                  const http = require('http');
                  const value = Math.floor(Math.random() * 10) + 1;
                  const data = JSON.stringify({event: 'rank-drift', value: value, threshold: 5});
                  const options = {
                    hostname: 'aioops-event-listener.production.svc.cluster.local',
                    port: 8080,
                    path: '/event',
                    method: 'POST',
                    headers: {
                      'Content-Type': 'application/json',
                      'Content-Length': data.length
                    }
                  };
                  const req = http.request(options, (res) => {
                    console.log('Event sent:', value, 'Status:', res.statusCode);
                  });
                  req.on('error', (e) => console.log('Error:', e.message));
                  req.write(data);
                  req.end();
                "
                sleep 60
              done
