apiVersion: v1
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
            grpc:
            thrift_binary:
            thrift_compact:
        zipkin:
        otlp:
          protocols:
            grpc:
            http:
    ingester:
      max_block_duration: 5m
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces
    usage_report:
      reporting_enabled: false
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"tempo.yaml":"server:\n  http_listen_port: 3200\ndistributor:\n  receivers:\n    jaeger:\n      protocols:\n        thrift_http:\n        grpc:\n        thrift_binary:\n        thrift_compact:\n    zipkin:\n    otlp:\n      protocols:\n        grpc:\n        http:\ningester:\n  max_block_duration: 5m\nstorage:\n  trace:\n    backend: local\n    local:\n      path: /tmp/tempo/traces\nusage_report:\n  reporting_enabled: false\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"tempo-config","namespace":"monitoring"}}
  creationTimestamp: "2025-10-25T22:43:27Z"
  name: tempo-config
  namespace: monitoring
  resourceVersion: "457673"
  uid: d67d65ae-dc87-46e2-8aad-57e444c4cacf
