apiVersion: apps/v1
kind: Deployment
metadata:
  name: dese-ea-plan
  namespace: dese-ea-plan-v5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dese-ea-plan
  template:
    metadata:
      labels:
        app: dese-ea-plan
        app.kubernetes.io/name: dese-ea-plan-v5
    spec:
      containers:
        - name: app
          image: python:3.11-alpine
          command:
            - sh
            - -c
          args:
            - |
              apk add --no-cache curl >/dev/null &&
              cat <<'PY' > /tmp/server.py
              from http.server import BaseHTTPRequestHandler, HTTPServer

              class Handler(BaseHTTPRequestHandler):
                  def do_GET(self):
                      if self.path == '/health':
                          self.send_response(200)
                          self.send_header('Content-Type', 'application/json')
                          self.end_headers()
                          self.wfile.write(b'{ status:healthy}')
                      else:
                          self.send_response(404)
                          self.end_headers()

              if __name__ == '__main__':
                  HTTPServer(('0.0.0.0', 3000), Handler).serve_forever()
              PY
              python /tmp/server.py
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dese-ea-plan
  namespace: dese-ea-plan-v5
spec:
  selector:
    app: dese-ea-plan
  ports:
    - port: 3000
      targetPort: 3000
