apiVersion: v1
kind: ConfigMap
metadata:
  name: seo-observer-config
  namespace: monitoring
data:
  LIGHTHOUSE_ENDPOINT: "http://lighthouse-headless.monitoring:3000/api/lighthouse"
  PROMETHEUS_PUSHGATEWAY: "http://prometheus.monitoring:9091"
  REFRESH_INTERVAL: "300"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seo-observer
  namespace: monitoring
  labels:
    app: seo-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seo-observer
  template:
    metadata:
      labels:
        app: seo-observer
    spec:
      containers:
        - name: seo-observer
          image: node:18-alpine
          command:
            - /bin/sh
            - -c
            - |
              npm install -g lighthouse
              echo "SEO Observer started - Lighthouse available"
              while true; do
                echo "SEO Observer running - $(date)"
                sleep 30
              done
          envFrom:
            - configMapRef:
                name: seo-observer-config
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: seo-observer
  namespace: monitoring
  labels:
    app: seo-observer
spec:
  selector:
    app: seo-observer
  ports:
    - name: http
      port: 8080
      targetPort: http
