apiVersion: v1
kind: ConfigMap
metadata:
  name: seo-observer-config
  namespace: monitoring
data:
  LIGHTHOUSE_ENDPOINT: "http://lighthouse-headless.monitoring:3000/api/lighthouse"
  PROMETHEUS_PUSHGATEWAY: "http://prometheus.monitoring:9091"
  REFRESH_INTERVAL: "300"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seo-observer
  namespace: monitoring
  labels:
    app: seo-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seo-observer
  template:
    metadata:
      labels:
        app: seo-observer
    spec:
      containers:
        - name: seo-observer
          image: node:18-alpine
          command:
            - /bin/sh
            - -c
            - |
              set -euo pipefail
              mkdir -p /app
              npm install -g lighthouse >/tmp/npm-install.log 2>&1
              cat <<'EOF' >/app/server.mjs
              import http from 'node:http';

              const startedAt = Date.now();

              const server = http.createServer((req, res) => {
                if (req.url === '/health') {
                  res.writeHead(200, { 'Content-Type': 'application/json' });
                  res.end(JSON.stringify({
                    status: 'ok',
                    timestamp: new Date().toISOString(),
                    uptimeSeconds: Math.floor((Date.now() - startedAt) / 1000)
                  }));
                  return;
                }

                res.writeHead(200, { 'Content-Type': 'text/plain' });
                res.end(`SEO Observer running - ${new Date().toISOString()}`);
              });

              server.listen(8080, () => {
                console.log('SEO Observer started - HTTP endpoint listening on port 8080');
              });

              setInterval(() => {
                console.log(`SEO Observer heartbeat - ${new Date().toISOString()}`);
              }, 30000);
              EOF
              node /app/server.mjs
          envFrom:
            - configMapRef:
                name: seo-observer-config
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: seo-observer
  namespace: monitoring
  labels:
    app: seo-observer
spec:
  selector:
    app: seo-observer
  ports:
    - name: http
      port: 8080
      targetPort: http
