# File: production/overlays/seo-observer/values.yaml
# Purpose: SEO Observer Prometheus entegrasyonu + AIOps event listener aktivasyonu

prometheus:
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    labels:
      release: prometheus
    endpoints:
      - port: http
        path: /metrics/seo
        scheme: http
        interval: 30s
        scrapeTimeout: 10s
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_label_app]
            targetLabel: app
            replacement: seo-observer

aioops:
  eventListener:
    enabled: true
    queue: seo-observer-events
    topic: rank-drift
    handlers:
      - type: anomalyDetection
        threshold: 5
        action: autoRemediate
