apiVersion: v1
kind: ServiceAccount
metadata:
  name: dese-ea-plan-v5
  namespace: dese-ea-plan-v5
  labels:
    app.kubernetes.io/name: dese-ea-plan-v5
    app.kubernetes.io/version: "5.0.0"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cpt-optimization
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dese-ea-plan-v5
  namespace: dese-ea-plan-v5
  labels:
    app.kubernetes.io/name: dese-ea-plan-v5
    app.kubernetes.io/version: "5.0.0"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cpt-optimization
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dese-ea-plan-v5
  namespace: dese-ea-plan-v5
  labels:
    app.kubernetes.io/name: dese-ea-plan-v5
    app.kubernetes.io/version: "5.0.0"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cpt-optimization
subjects:
- kind: ServiceAccount
  name: dese-ea-plan-v5
  namespace: dese-ea-plan-v5
roleRef:
  kind: Role
  name: dese-ea-plan-v5
  apiGroup: rbac.authorization.k8s.io
