apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform applications (monitoring, security, seo-ops)
  sourceRepos:
    - 'https://github.com/desesonpro/gitops.git'
    - 'https://github.com/desesonpro/*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: platform-admin
      description: Platform administration role
      policies:
        - p, proj:platform:platform-admin, applications, *, platform/*, allow
        - p, proj:platform:platform-admin, repositories, *, *, allow
      groups:
        - platform-admins
    - name: platform-developer
      description: Platform developer role
      policies:
        - p, proj:platform:platform-developer, applications, get, platform/*, allow
        - p, proj:platform:platform-developer, applications, sync, platform/*, allow
      groups:
        - platform-developers
