apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: corp-store
spec:
  provider:
    vault:
      server: "https://vault.corp.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "argocd"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-admin
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: corp-store
    kind: ClusterSecretStore
  target:
    name: argocd-admin
    creationPolicy: Owner
  data:
  - secretKey: admin.password
    remoteRef:
      key: /platform/argocd/admin_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: corp-store
    kind: ClusterSecretStore
  target:
    name: monitoring-secrets
    creationPolicy: Owner
  data:
  - secretKey: grafana.admin-password
    remoteRef:
      key: /platform/monitoring/grafana_admin_password
  - secretKey: prometheus.basic-auth
    remoteRef:
      key: /platform/monitoring/prometheus_basic_auth
