apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dese-ea-plan-v5

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - secret.yaml
  - namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: cpt-optimization
      version: base

images:
  - name: dese-ea-plan-v5
    newName: ghcr.io/desewebv5/dese-ea-plan-v5
    newTag: latest

configMapGenerator:
  - name: dese-ea-plan-v5-config
    files:
      - config.env

