receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Probabilistic sampling: 10% of traces
  probabilistic_sampler:
    sampling_percentage: 10

  # Tail sampling: Always sample errors and feedback requests
  tail_sampling:
    policies:
      # Error traces
      - name: errors
        type: status_code
        status_code:
          status_codes:
            - ERROR

      # Feedback endpoint traces
      - name: feedback-path
        type: string_attribute
        string_attribute:
          key: http.target
          values:
            - '/api/v1/aiops/feedback'

      # Auto-remediation actions
      - name: remediation-actions
        type: string_attribute
        string_attribute:
          key: aiops.action
          values:
            - 'remediate'
            - 'drift_detection'

      # AIOps telemetry
      - name: aiops-telemetry
        type: string_attribute
        string_attribute:
          key: aiops.telemetry
          values:
            - 'collect'
            - 'detect'

exporters:
  # Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Loki for logs
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      resource:
        service.name: "dese-ea-plan-v5"
        deployment.environment: "production"

  # Jaeger/Tempo
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler, tail_sampling]
      exporters: [otlp, prometheus]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, otlp]

    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]

