apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-cloud-federation-service
  namespace: ea-plan-v6.1-prod
  labels:
    app: multi-cloud-federation-service
    version: "1.0.0"
    phase: "blueprint"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-cloud-federation-service
  template:
    metadata:
      labels:
        app: multi-cloud-federation-service
        version: "1.0.0"
        phase: "blueprint"
    spec:
      containers:
      - name: multi-cloud-federation-service
        image: ghcr.io/your-org/multi-cloud-federation-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: CLOUD_PROVIDERS
          value: "aws,azure,gcp,private"
        - name: FEDERATION_STRATEGY
          value: "adaptive"
        - name: GLOBAL_REGIONS
          value: "us-east-1,eu-west-1,ap-southeast-1"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-federation-service
  namespace: ea-plan-v6.1-prod
  labels:
    app: multi-cloud-federation-service
spec:
  selector:
    app: multi-cloud-federation-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: multi-cloud-federation-service-hpa
  namespace: ea-plan-v6.1-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: multi-cloud-federation-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-security-service
  namespace: ea-plan-v6.1-prod
  labels:
    app: quantum-security-service
    version: "1.0.0"
    phase: "blueprint"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quantum-security-service
  template:
    metadata:
      labels:
        app: quantum-security-service
        version: "1.0.0"
        phase: "blueprint"
    spec:
      containers:
      - name: quantum-security-service
        image: ghcr.io/your-org/quantum-security-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: QUANTUM_ALGORITHMS
          value: "kyber,dilithium,falcon,sphincs"
        - name: SECURITY_LEVELS
          value: "level_1,level_3,level_5"
        - name: QUANTUM_NETWORK_ENABLED
          value: "true"
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "1500m"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: quantum-security-service
  namespace: ea-plan-v6.1-prod
  labels:
    app: quantum-security-service
spec:
  selector:
    app: quantum-security-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quantum-security-service-hpa
  namespace: ea-plan-v6.1-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quantum-security-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-twins-service
  namespace: ea-plan-v6.1-prod
  labels:
    app: digital-twins-service
    version: "1.0.0"
    phase: "blueprint"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: digital-twins-service
  template:
    metadata:
      labels:
        app: digital-twins-service
        version: "1.0.0"
        phase: "blueprint"
    spec:
      containers:
      - name: digital-twins-service
        image: ghcr.io/your-org/digital-twins-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: TWIN_TYPES
          value: "physical_asset,process,system,environment,human,organization"
        - name: COGNITIVE_MODELS_ENABLED
          value: "true"
        - name: REAL_TIME_SYNC
          value: "true"
        resources:
          requests:
            cpu: "400m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: digital-twins-service
  namespace: ea-plan-v6.1-prod
  labels:
    app: digital-twins-service
spec:
  selector:
    app: digital-twins-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: digital-twins-service-hpa
  namespace: ea-plan-v6.1-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: digital-twins-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-ethics-service
  namespace: ea-plan-v6.1-prod
  labels:
    app: ai-ethics-service
    version: "1.0.0"
    phase: "blueprint"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-ethics-service
  template:
    metadata:
      labels:
        app: ai-ethics-service
        version: "1.0.0"
        phase: "blueprint"
    spec:
      containers:
      - name: ai-ethics-service
        image: ghcr.io/your-org/ai-ethics-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: ETHICS_PRINCIPLES
          value: "fairness,transparency,accountability,privacy,safety"
        - name: BIAS_DETECTION_ENABLED
          value: "true"
        - name: COMPLIANCE_MONITORING
          value: "continuous"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-ethics-service
  namespace: ea-plan-v6.1-prod
  labels:
    app: ai-ethics-service
spec:
  selector:
    app: ai-ethics-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-ethics-service-hpa
  namespace: ea-plan-v6.1-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-ethics-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligence-fabric-service
  namespace: ea-plan-v6.1-prod
  labels:
    app: intelligence-fabric-service
    version: "1.0.0"
    phase: "blueprint"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: intelligence-fabric-service
  template:
    metadata:
      labels:
        app: intelligence-fabric-service
        version: "1.0.0"
        phase: "blueprint"
    spec:
      containers:
      - name: intelligence-fabric-service
        image: ghcr.io/your-org/intelligence-fabric-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: INTELLIGENCE_TYPES
          value: "predictive,prescriptive,diagnostic,descriptive,cognitive,adaptive"
        - name: LEARNING_MODES
          value: "supervised,unsupervised,reinforcement,federated,transfer,continual"
        - name: ORCHESTRATION_STRATEGY
          value: "adaptive"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2500m"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: intelligence-fabric-service
  namespace: ea-plan-v6.1-prod
  labels:
    app: intelligence-fabric-service
spec:
  selector:
    app: intelligence-fabric-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: intelligence-fabric-service-hpa
  namespace: ea-plan-v6.1-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: intelligence-fabric-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: ea-plan-v6.1-prod
  labels:
    name: ea-plan-v6.1-prod
    phase: blueprint
    version: "6.1"
---
apiVersion: v1
kind: Secret
metadata:
  name: ea-plan-v6.1-secrets
  namespace: ea-plan-v6.1-prod
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  quantum-key-manager-token: <base64-encoded-token>
  multi-cloud-api-key: <base64-encoded-key>
  digital-twin-db-password: <base64-encoded-password>
  ai-ethics-api-key: <base64-encoded-key>
  intelligence-fabric-token: <base64-encoded-token>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ea-plan-v6.1-config
  namespace: ea-plan-v6.1-prod
data:
  # Global configuration for EA Plan v6.1 Blueprint
  federation-strategy: "adaptive"
  quantum-security-level: "level_5"
  digital-twin-sync-frequency: "real_time"
  ethics-compliance-mode: "continuous"
  intelligence-orchestration: "adaptive"
  global-regions: "us-east-1,eu-west-1,ap-southeast-1,us-west-2"
  cloud-providers: "aws,azure,gcp,private"
  monitoring-enabled: "true"
  logging-level: "info"
