apiVersion: v1
kind: Service
metadata:
  name: cpt-ajan-backend
  namespace: dese-ea-plan-v5
  labels:
    app: cpt-ajan-backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: cpt-ajan-backend

