apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpt-ajan-backend
  namespace: dese-ea-plan-v5
  labels:
    app: cpt-ajan-backend
    version: v5.6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpt-ajan-backend
  template:
    metadata:
      labels:
        app: cpt-ajan-backend
        version: v5.6
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: dese-ea-plan-v5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: backend
        image: ghcr.io/your-org/cpt-ajan-backend:v5.6-stable
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

