apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpt-ajan-frontend
  namespace: dese-ea-plan-v5
  labels:
    app: cpt-ajan-frontend
    version: v5.6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpt-ajan-frontend
  template:
    metadata:
      labels:
        app: cpt-ajan-frontend
        version: v5.6
    spec:
      containers:
      - name: frontend
        image: ghcr.io/your-org/cpt-ajan-frontend:v5.6-stable
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "http://cpt-ajan-backend:8080/api/v1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

