apiVersion: apps/v1
kind: Deployment
metadata:
  name: seo-observer
  namespace: monitoring
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: seo-observer
          envFrom:
            - configMapRef:
                name: seo-config
