apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    environment: production
    team: security
    cost-center: security
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-config
  namespace: kyverno
data:
  environment: production
  cluster: desewebv5
  policy-mode: enforce
