apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpt-ajan-backend-hpa
  namespace: ea-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpt-ajan-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpt-ajan-frontend-hpa
  namespace: ea-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpt-ajan-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
