apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpt-ajan
  namespace: argocd
  labels:
    app: cpt-ajan
    version: v1.0.0
spec:
  project: platform
  source:
    repoURL: https://github.com/desesonpro/cptajani.git
    targetRevision: main
    path: ops/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ea-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform applications (monitoring, security, cpt-ajan)
  sourceRepos:
  - 'https://github.com/desesonpro/cptajani.git'
  - 'https://github.com/desesonpro/*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: platform-admin
    description: Platform administration role
    policies:
    - p, proj:platform:platform-admin, applications, *, platform/*, allow
    - p, proj:platform:platform-admin, repositories, *, *, allow
    groups:
    - platform-admins
